# -*- coding: utf-8 -*-
"""ReDI_COVID19_Forecast_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oj6ksGZAu2Nd2knMsBqlSwdVJv0NJjiX
"""

# Install packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.io as pio

df = pd.read_excel("/content/sample_data/COVID_Data.xlsx")

df.head()

df.info()

df.shape

df.isnull().sum()

print(df.columns)

active = df['Active cases']
plt.show()

plt.figure(figsize=(15, 6))
plt.plot(active, label='Daily Active Cases', color='green')
plt.title('Active COVID-19 Cases from September 2020 to Feb 2021 in Bangalore')
plt.xlabel('Date')
plt.ylabel('Active cases')
plt.legend()
plt.tight_layout()
plt.grid(True)
plt.show()

df['Date'] = pd.to_datetime(df['Date'])
#chnage the format of Date on y axis
df = df.sort_values('Date')
df.set_index('Date', inplace=True)

active = df['Active cases']

#Focus only on prediction of Active cases in Bangalore
plt.figure(figsize=(12,5))
plt.plot(active, label='Daily Active Cases', color='green')
plt.title("Active COVID-19 Cases from September 2020 to Feb 2021 in Bangalore")
plt.xlabel("Date")
plt.ylabel("Active Cases")
plt.legend()
plt.grid(True)

plt.show()

active = df['Active cases']
positive = df['Positive cases']
recovered = df['Recovered']
death = df['Death']

#plot for all the cases
plt.figure(figsize=(10, 6))
plt.plot(df['Active cases'], label='Active cases', color='green')
plt.plot(df['Positive cases'], label='Positive cases', color='orange')
plt.plot(df['Recovered'], label='Recovered cases', color='blue')
plt.plot(df['Death'], label='Death', color='red')
plt.title('COVID-19 Case Trends in Bangalore')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.grid(True)
plt.show()

start_date = "2020-09-01"
end_date = "2021-03-31"
filtered_df = df.loc[start_date:end_date]

monthly_avg = df['Active cases'].resample('M').mean()

#Resample by month and calculate mean
plt.figure(figsize=(14, 6))
plt.plot(monthly_avg.index, monthly_avg, marker='o', color='green', label='Monthly Avg Active case')
plt.title('Monthly Average Load')
plt.xlabel('Month')
plt.ylabel('Average Active case')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

weekly_avg = df['Active cases'].resample('W').mean()

plt.figure(figsize=(14, 6))
plt.plot(weekly_avg.index, weekly_avg, marker='*', color='green', label='Weekly Avg Active case')
plt.title('Weekly Average Load')
plt.xlabel('Weekly')
plt.ylabel('Average Active case')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

df['DayOfWeek'] = df.index.day_name()

plt.figure(figsize=(12,6))
df.boxplot(column='Active cases', by='DayOfWeek', grid=False)
plt.title("Active Cases by Day of Week")
plt.xlabel("Day of Week")
plt.ylabel("Active cases")
plt.xticks(rotation=45)
plt.show()

# 7-day moving average
ma7 = active.rolling(window=7).mean()plt.figure(figsize=(12,5))

plt.plot(active, label='Daily Active Cases', color='blue')
plt.plot(ma7, label='7-Day Moving Average', color='red')
plt.title("Active COVID-19 Cases Over Time")
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)

plt.show()

# 14-day moving average (smooth trend)
ma14 = active.rolling(window=14).mean()

plt.figure(figsize=(12,5))
plt.plot(active, label='Daily Active Cases', color='blue')
plt.plot(ma14, label='14-Day Moving Average', color='red')
plt.title("Active COVID-19 Cases Over Time")
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)

plt.show()

#Decompose the Time Series
from statsmodels.tsa.seasonal import seasonal_decompose

decomp = seasonal_decompose(df['Active cases'], model='additive', period=7, extrapolate_trend='freq')
decomp.plot()
plt.show()

active.index = pd.to_datetime(active.index, errors='coerce')

print(active.index)

print(active.columns)

# Create training and testing data sets
train_end = '2021-02-28'
train = active.loc[:train_end]
test = active.loc['2021-03-01':]
print("Train length:", len(train))
print("Test length:", len(test))

!pip install pmdarima
import pmdarima as pm

# auto-arima for model selection for weekly
model_auto = pm.auto_arima(train,
                           seasonal=True,
                           m=7,
                           trace=True,
                           error_action='ignore',
                           suppress_warnings=True,
                           stepwise=True)
print(model_auto.summary())

model = pm.ARIMA(order=(1, 1, 2), seasonal_order=(1, 0, 0, 7))
model.fit(train)

# Forecast the next 7 days
forecast_7days = model.predict(n_periods=7)

# Forecast the next 14 days
forecast_14days = model.predict(n_periods=14)

# Forecast the next 30 days
forecast_30days = model.predict(n_periods=30)

print("Forecast for the next 7 days:", forecast_7days)
print("Forecast for the next 14 days:", forecast_14days)
print("Forecast for the next 30 days:", forecast_30days)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

y_true = test[:7]
y_pred_7days = forecast_7days

mae_7 = mean_absolute_error(y_true, y_pred_7days)
rmse_7 = np.sqrt(mean_squared_error(y_true, y_pred_7days))

print("7 Days MAE:", mae_7)
print("7 Days RMSE:", rmse_7)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

y_true = test[:14]
y_pred_14days = forecast_14days

mae_14 = mean_absolute_error(y_true, y_pred_14days)
rmse_14 = np.sqrt(mean_squared_error(y_true, y_pred_14days))

print("14 Days MAE:", mae_14)
print("14 Days RMSE:", rmse_14)

plt.figure(figsize=(10, 6))
plt.plot(active.index, active, label='Active Cases')
forecast_dates_7 = pd.date_range(start=active.index[-1], periods=8, freq='D')
plt.plot(forecast_dates_7, np.concatenate([train[-1:], forecast_7days]), label='Forecast (7 Days)', color='orange')
plt.title('COVID-19 Active Cases Forecast')
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(active.index, active, label='Active Cases')
forecast_dates_14 = pd.date_range(start=active.index[-1], periods=15, freq='D')
plt.plot(forecast_dates_14, np.concatenate([train[-1:], forecast_14days]), label='Forecast (14 Days)', color='green')
plt.title('COVID-19 Active Cases Forecast')
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(active.index, active, label='Active Cases')
forecast_dates_30 = pd.date_range(start=active.index[-1], periods=31, freq='D')
plt.plot(forecast_dates_30, np.concatenate([train[-1:], forecast_30days]), label='Forecast (30 Days)', color='blue')
plt.title('COVID-19 Active Cases Forecast')
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)
plt.show()

print(active.index)

print(active.head())

forecast_dates_7 = pd.date_range(start=train.index[-1], periods=8, freq='D')
forecast_7days_full = np.concatenate([train[-1:], forecast_7days])
plt.figure(figsize=(10, 6))
plt.plot(active.index, active, label='Active Cases', color='blue')
plt.plot(forecast_dates_7, forecast_7days_full, label='Forecast (7 Days)', color='orange')
plt.title('COVID-19 Active Cases Forecast (Next 7 Days)')
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)
plt.show()

forecast_dates_14 = pd.date_range(start=train.index[-1], periods=15, freq='D')
forecast_14days_full = np.concatenate([train[-1:], forecast_14days])
plt.figure(figsize=(10, 6))
plt.plot(active.index, active, label='Active Cases', color='blue')
plt.plot(forecast_dates_14, forecast_14days_full, label='Forecast (14 Days)', color='orange')
plt.title('COVID-19 Active Cases Forecast (Next 14 Days)')
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)
plt.show()

forecast_dates_30 = pd.date_range(start=train.index[-1], periods=31, freq='D')
forecast_30days_full = np.concatenate([train[-1:], forecast_30days])
plt.figure(figsize=(12, 8))
plt.plot(active.index, active, label='Active Cases', color='blue')
plt.plot(forecast_dates_30, forecast_30days_full, label='Forecast (30 Days)', color='orange')
plt.title('COVID-19 Active Cases Forecast vs. Actual (Next 30 Days)')
plt.xlabel('Date')
plt.ylabel('Active Cases')
plt.legend()
plt.grid(True)
plt.show()

!pip install plotly

import plotly.express as px
fig = px.line(df.reset_index(), x='Date', y='Active cases', title='Interactive Load Plot')
fig.show()

import plotly.express as px
fig = px.line(df.reset_index(), x='Date', y='Positive cases', title='Interactive Load Plot')
fig.show()

forecast_test = model.predict(n_periods=len(test))
test_forecast = pd.Series(forecast_test.values, index=test.index)
plt.figure(figsize=(14,6))
plt.plot(train.index, train, label='Training Data', color='blue')
plt.plot(test.index, test, label='Actual Test Data', color='green')
plt.plot(test_forecast.index, test_forecast, label='Forecast', color='orange', linestyle='--')
plt.axvline(train.index[-1], color='black', linestyle=':', label='Train/Test Split')
plt.title("Training vs Test vs Forecast")
plt.xlabel("Date")
plt.ylabel("Active Cases")
plt.legend()
plt.grid(True)
plt.show()